### ISSUE TITLE
Error occurred while enabling Graves v4.9.1

### ISSUE THREAD

**Issue by analoghumanoid** [AvarionMC/graves#15]
Updated from PaperMC 1.20.4 to 1.20.6 and Graves v4.9.1 is now failing to enable. 

> [11:56:41 INFO]: [Graves] Enabling Graves v4.9.1
[11:56:41 INFO]: [Graves] Integration: Hooked into MiniMessage.
[11:56:41 ERROR]: Error occurred while enabling Graves v4.9.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at Graves-4.9.1.jar/com.ranull.graves.manager.VersionManager.<init>(VersionManager.java:23) ~[Graves-4.9.1.jar:?]
        at Graves-4.9.1.jar/com.ranull.graves.Graves.onEnable(Graves.java:66) ~[Graves-4.9.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:56:41 INFO]: [Graves] Disabling Graves v4.9.1
[11:56:42 ERROR]: Error occurred while disabling Graves v4.9.1
java.lang.NullPointerException: Cannot invoke "com.ranull.graves.manager.DataManager.closeConnection()" because "this.dataManager" is null
        at Graves-4.9.1.jar/com.ranull.graves.Graves.onDisable(Graves.java:95) ~[Graves-4.9.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by svaningelgem** [comment]
Ok, this is annoying!

According to the spigot builds, these are the minimal java versions:
```
    "1.8": (7, 8),
    "1.8.3": (7, 8),
    "1.8.4": (7, 8),
    "1.8.5": (7, 8),
    "1.8.6": (7, 8),
    "1.8.7": (7, 8),
    "1.8.8": (7, 8),
    "1.9": (7, 8),
    "1.9.2": (7, 8),
    "1.9.4": (7, 8),
    "1.10": (7, 8),
    "1.10.2": (7, 8),
    "1.11": (7, 8),
    "1.11.1": (7, 8),
    "1.11.2": (7, 8),
    "1.12": (8, 8),
    "1.12.1": (8, 9),
    "1.12.2": (8, 10),
    "1.13": (8, 11),
    "1.13.1": (8, 11),
    "1.13.2": (8, 12),
    "1.14": (8, 12),
    "1.14.1": (8, 12),
    "1.14.2": (8, 12),
    "1.14.3": (8, 12),
    "1.14.4": (8, 13),
    "1.15": (8, 13),
    "1.15.1": (8, 13),
    "1.15.2": (8, 14),
    "1.16.1": (8, 14),
    "1.16.2": (8, 14),
    "1.16.3": (8, 15),
    "1.16.4": (8, 15),
    "1.16.5": (8, 16),
    "1.17": (16, 16),
    "1.17.1": (16, 17),
    "1.18": (17, 17),
    "1.18.1": (17, 17),
    "1.18.2": (17, 18),
    "1.19": (17, 18),
    "1.19.1": (17, 18),
    "1.19.2": (17, 19),
    "1.19.3": (17, 20),
    "1.19.4": (17, 20),
    "1.20": (17, 21),
    "1.20.1": (17, 21),
    "1.20.2": (17, 21),
    "1.20.4": (17, 22),
    "1.20.6": (21, 22),
```

I will make the new version with Java 21, and only support 1.20.*. If you need the older version, it'll be a previous one.

For this, I will also introduce a new major in order to make this clear.

**Comment by svaningelgem** [comment]
I was able to work around with minimal changes. As soon as everything is built, I'll upload it to Spigot.
