### ISSUE TITLE
Error to die

### ISSUE THREAD

**Issue by Astralymc** [AvarionMC/graves#26]
```
[19:01:30 INFO]: [Essentials] CONSOLE issued server command: /kill Salchii2k
[19:01:30 ERROR]: Could not pass event PlayerDeathEvent to Graves v4.9
java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
        at com.ranull.graves.util.SkinUtil.getTexture(SkinUtil.java:48) ~[Graves-4.9 (1).jar:?]
        at com.ranull.graves.listener.EntityDeathListener.onEntityDeath(EntityDeathListener.java:297) ~[Graves-4.9 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor810.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"1954a51"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"1954a51"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:76) ~[?:git-UniverseSpigot-"1954a51"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1019) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1034) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:122) ~[?:git-UniverseSpigot-"1954a51"]
        at com.earth2me.essentials.commands.Commandkill.updatePlayer(Commandkill.java:37) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.lambda$loopOnlinePlayers$1(EssentialsLoopCommand.java:72) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayersConsumer(EssentialsLoopCommand.java:115) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.commands.EssentialsLoopCommand.loopOnlinePlayers(EssentialsLoopCommand.java:72) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.commands.Commandkill.run(Commandkill.java:23) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:869) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:770) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1002) ~[?:git-UniverseSpigot-"1954a51"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:987) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:520) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:468) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1533) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1234) ~[?:git-UniverseSpigot-"1954a51"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[?:git-UniverseSpigot-"1954a51"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by Astralymc** [comment]
https://mclo.gs/XYc1yP3

**Comment by Astralymc** [comment]
I tried using paper, since I thought maybe universespigot is not supported but it still happens to me

**Comment by svaningelgem** [comment]
Please upgrade your plugin. This has been fixed since release 4.9.1.

**Comment by Astralymc** [comment]
Where is it updated? Since I downloaded it from spigot

**Comment by svaningelgem** [comment]
You can download it from: https://www.spigotmc.org/resources/graves.116202/ (which is a new URL as "Ranull" didn't update his plugin any longer)

**Comment by svaningelgem** [comment]
Duplicate of #13
