### ISSUE TITLE
Oraxen furniture Problem

### ISSUE THREAD

**Issue by SlicedWatermelon** [AvarionMC/graves#45]
### Checks

- [X] I have checked that this issue has not already been reported (even among closed issues).
- [X] I have confirmed this bug exists on the [latest version](https://www.spigotmc.org/resources/graves.116202/history).

### Version

4.9.4

### Server version

1.21

### Plugin list

 AutoMessageSystem, BetterRTP, BlockRewards, Citizens, CMILib, CrazyAuctions, CustomCrops, CustomFishing, DecentHolograms, DeluxeMenus, DeluxeTags, Essentials, EssentialsSpawn, Graves, InvisibleItemFrames, Jobs, LuckPerms, MiniMOTD, Multiverse-Core, Oraxen, PL-Hide, PlaceholderAPI, PlayerPoints, PlayerWarps, PlugManX, ProtocolLib, SilktouchSpawners, TAB, Vault, VentureChat, WorldEdit, WorldGuard

### Expected behavior

Right clicking Oraxen furniture grave to open grave

### Actual behavior

Right clicking Oraxen furniture grave doesnt do anything, only when I destroy oraxen furniture it lets me open invisible grave

### Stacktrace if applicable (no screenshots!)

```
[13:39:37 ERROR]: Could not pass event PlayerDeathEvent to Graves v4.9.4
java.lang.ClassCastException: class org.bukkit.craftbukkit.entity.CraftItemDisplay cannot be cast to class org.bukkit.entity.ItemFrame (org.bukkit.craftbukkit.entity.CraftItemDisplay and org.bukkit.entity.ItemFrame are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
at Graves-4.9.4.jar/org.avarion.graves.integration.Oraxen.createFurniture(Oraxen.java:92) ~[Graves-4.9.4.jar:?]
at Graves-4.9.4.jar/org.avarion.graves.manager.GraveManager.placeGrave(GraveManager.java:329) ~[Graves-4.9.4.jar:?]
at Graves-4.9.4.jar/org.avarion.graves.listener.EntityDeathListener.execute(EntityDeathListener.java:498) ~[Graves-4.9.4.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-37-dd49fba]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-37-dd49fba]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-37-dd49fba]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1021) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1037) ~[paper-1.21.jar:1.21-37-dd49fba]
at org.bukkit.craftbukkit.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:122) ~[paper-1.21.jar:1.21-37-dd49fba]
at EssentialsX-2.21.0-dev+102-fcf6e64.jar/com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.java:19) ~[EssentialsX-2.21.0-dev+102-fcf6e64.jar:?]
at EssentialsX-2.21.0-dev+102-fcf6e64.jar/com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[EssentialsX-2.21.0-dev+102-fcf6e64.jar:?]
at EssentialsX-2.21.0-dev+102-fcf6e64.jar/com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:898) ~[EssentialsX-2.21.0-dev+102-fcf6e64.jar:?]
at EssentialsX-2.21.0-dev+102-fcf6e64.jar/com.earth2me.essentials.Essentials.onCommand(Essentials.java:797) ~[EssentialsX-2.21.0-dev+102-fcf6e64.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.21.jar:1.21-37-dd49fba]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.Commands.performCommand(Commands.java:353) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.commands.Commands.performCommand(Commands.java:335) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2147) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2121) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-37-dd49fba]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Additional information

Video of problem:
https://streamable.com/8rzoxs

**Comment by svaningelgem** [comment]
Hi @SlicedWatermelon , I received the issue and will look into it. (fyi: the video isn't working?)

**Comment by SlicedWatermelon** [comment]
> Hi @SlicedWatermelon , I received the issue and will look into it. (fyi: the video isn't working?)

Fixed
