### ISSUE TITLE
Error occurred while enabling Graves v4.9.4

### ISSUE THREAD

**Issue by Romainof** [AvarionMC/graves#46]
### Checks

- [x] I have checked that this issue has not already been reported (even among closed issues).
- [X] I have confirmed this bug exists on the [latest version](https://www.spigotmc.org/resources/graves.116202/history).

### Version

4.9.4

### Server version

1.21

### Plugin list

Plugins (8): AutoSaveWorld, WorldEdit, floodgate, WorldGuard, WorldGuardExtraFlags, Graves, SkinsRestorer, Geyser-Spigot

### Expected behavior

The plugin should create a grave.

### Actual behavior

The plugin does not create tombs but the in-game commands are functional. Since the last update of 4.9.2 --> 4.9.4, the plugin no longer works.

### Stacktrace if applicable (no screenshots!)

[05:16:23] [Server thread/ERROR]: Error occurred while enabling Graves v4.9.4 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "priorityStr" is null
	at org.avarion.graves.Graves.getEventPriority(Graves.java:245) ~[?:?]
	at org.avarion.graves.Graves.registerListeners(Graves.java:211) ~[?:?]
	at org.avarion.graves.Graves.onEnable(Graves.java:97) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.reload(CraftServer.java:1005) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at org.bukkit.Bukkit.reload(Bukkit.java:867) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchCommand(CraftServer.java:913) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at org.bukkit.craftbukkit.v1_21_R1.CraftServer.dispatchServerCommand(CraftServer.java:898) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.dedicated.DedicatedServer.br(DedicatedServer.java:431) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.dedicated.DedicatedServer.c(DedicatedServer.java:407) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1321) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4244-Spigot-0a642bd-13ece47]
	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]

**Comment by svaningelgem** [comment]
Thanks for your report.
In the short run, you can add this to your `config.yml` file under the `settings` section:
```yaml
  listener-priority:
    death: MONITOR
```

**Comment by svaningelgem** [comment]
This will be released as part of 4.9.5 somewhere next week. But for now you can apply the configuration fix mentioned above to remove the error.

**Comment by Romainof** [comment]
Thanks for your support!
