### ISSUE TITLE
Graves not working

### ISSUE THREAD

**Issue by AstroNott69** [AvarionMC/graves#81]
### Checks

- [X] I have checked that this issue has not already been reported (even among closed issues).
- [X] I have confirmed this bug exists on the [latest version](https://www.spigotmc.org/resources/graves.116202/history).
- [ ] I just click random checkboxes without actually reading them.

### Version

4.9.5

### Server version

1.21.1

### Plugin list

AFKPlus
AnimatedScoreboard
Graves
GSit
HeadDrop
InteractionVisualizer
OnePlayerSleep
PlaceholderAPI
ProtocolLib
SkinsRestorer
TabTPS

### Expected behavior

i expect that it would work like normally

### Actual behavior

when player died, it only drop the default steve head on the ground and cannot be interactable

### Stacktrace if applicable (no screenshots!)
```
[21:19:27 ERROR]: Could not pass event EntityDeathEvent to HeadDrop v5.2.1
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
	at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.mutateItemMeta(SkullCreator.java:90) ~[HeadDrop.jar:?]
	at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.itemWithBase64(SkullCreator.java:55) ~[HeadDrop.jar:?]
	at HeadDrop.jar/me.rrs.headdrop.util.SkullCreator.createSkullWithBase64(SkullCreator.java:32) ~[HeadDrop.jar:?]
	at HeadDrop.jar/me.rrs.headdrop.database.EntityHead.getSkull(EntityHead.java:203) ~[HeadDrop.jar:?]
	at HeadDrop.jar/me.rrs.headdrop.listener.EntityDeath.lambda$populateEntityActions$62(EntityDeath.java:1332) ~[HeadDrop.jar:?]
	at HeadDrop.jar/me.rrs.headdrop.listener.EntityDeath.entityDropHeadEvent(EntityDeath.java:150) ~[HeadDrop.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor225.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-82-1348e44]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:998) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1878) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1781) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:271) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:236) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by DennisWolff** [comment]
I have the same issue atm.

**Comment by svaningelgem** [comment]
I don't see anywhere "graves" in this stack trace? So to me it looks more like a "HeadDrop" issue?
Or is there a specific way to reproduce this?

What I'm thinking is that there is a bug in HeadDrop, which causes the server to eat the necessary events that Graves need to make things interact-able?

**Comment by DennisWolff** [comment]
For me its saying this [Graves] Update: Outdated version detected 4.9.5, latest version is 0.0.0, https://www.spigotmc.org/resources/116202/

**Comment by AstroNott69** [comment]
> I don't see anywhere "graves" in this stack trace? So to me it looks more like a "HeadDrop" issue? Or is there a specific way to reproduce this?
> 
> What I'm thinking is that there is a bug in HeadDrop, which causes the server to eat the necessary events that Graves need to make things interact-able?

my bad i copy the wrong log. this is the correct one:

<html>
<body>

[18:10:00] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Graves v4.9.5
--
235 | java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.block.CraftSkull.profile to com.mojang.authlib.GameProfile
236 | at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
237 | at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
238 | at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
239 | at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
240 | at Graves-4.9.5.jar/org.avarion.graves.util.SkinUtil.setSkullBlockTexture(SkinUtil.java:50) ~[Graves-4.9.5.jar:?]
241 | at Graves-4.9.5.jar/org.avarion.graves.compatibility.CompatibilityBlockData.updateSkullBlock(CompatibilityBlockData.java:111) ~[Graves-4.9.5.jar:?]
242 | at Graves-4.9.5.jar/org.avarion.graves.compatibility.CompatibilityBlockData.setBlockData(CompatibilityBlockData.java:63) ~[Graves-4.9.5.jar:?]
243 | at Graves-4.9.5.jar/org.avarion.graves.manager.BlockManager.createBlock(BlockManager.java:67) ~[Graves-4.9.5.jar:?]
244 | at Graves-4.9.5.jar/org.avarion.graves.manager.GraveManager.placeGrave(GraveManager.java:291) ~[Graves-4.9.5.jar:?]
245 | at Graves-4.9.5.jar/org.avarion.graves.listener.EntityDeathListener.execute(EntityDeathListener.java:490) ~[Graves-4.9.5.jar:?]
246 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-82-1348e44]
247 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
248 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
249 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
250 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
251 | at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1030) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
252 | at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1038) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
253 | at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
254 | at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
255 | at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
256 | at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
257 | at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:271) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
258 | at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:236) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
259 | at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
260 | at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
261 | at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
262 | at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
263 | at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
264 | at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
265 | at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
266 | at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
267 | at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
268 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
269 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
270 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
271 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
272 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
273 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]


</body>
</html>

[18:10:00] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Graves v4.9.5
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.block.CraftSkull.profile to com.mojang.authlib.GameProfile
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
	at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
	at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
	at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
	at Graves-4.9.5.jar/org.avarion.graves.util.SkinUtil.setSkullBlockTexture(SkinUtil.java:50) ~[Graves-4.9.5.jar:?]
	at Graves-4.9.5.jar/org.avarion.graves.compatibility.CompatibilityBlockData.updateSkullBlock(CompatibilityBlockData.java:111) ~[Graves-4.9.5.jar:?]
	at Graves-4.9.5.jar/org.avarion.graves.compatibility.CompatibilityBlockData.setBlockData(CompatibilityBlockData.java:63) ~[Graves-4.9.5.jar:?]
	at Graves-4.9.5.jar/org.avarion.graves.manager.BlockManager.createBlock(BlockManager.java:67) ~[Graves-4.9.5.jar:?]
	at Graves-4.9.5.jar/org.avarion.graves.manager.GraveManager.placeGrave(GraveManager.java:291) ~[Graves-4.9.5.jar:?]
	at Graves-4.9.5.jar/org.avarion.graves.listener.EntityDeathListener.execute(EntityDeathListener.java:490) ~[Graves-4.9.5.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-82-1348e44]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:1030) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:1038) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1586) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:271) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:[236](https://aternos.org/log/#L236)) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by AstroNott69** [comment]
> For me its saying this [Graves] Update: Outdated version detected 4.9.5, latest version is 0.0.0, https://www.spigotmc.org/resources/116202/

yes same, i got that error log also

**Comment by svaningelgem** [comment]
That outdated thing has been fixed in #78 already (but didn't release it yet).

**Comment by svaningelgem** [comment]
Does either of you have Discord? Can you add me: BumbaBot. Then I'll send you the latest snapshot version to see if the error is reproducible there...

**Comment by flanigomik** [comment]
can report this is also happening to me now as well. just started today out of nowhere. could it be related to a paper update? i just updated to build 83

**Comment by svaningelgem** [comment]
The issue has been resolved now. 1.21.1 had a different way of handling the skull textures. I've added the proper logic for it now.

It'll be uploaded shortly.

Please check if it's working fine at your side (it was at mine at least).

**Comment by AstroNott69** [comment]
> The issue has been resolved now. 1.21.1 had a different way of handling the skull textures. I've added the proper logic for it now.
> 
> It'll be uploaded shortly.
> 
> Please check if it's working fine at your side (it was at mine at least).

thank you very much man. will check it later when im home

**Comment by flanigomik** [comment]
can confirm that the update rectified the issue for me, thank you very much
